In [4]:
import numpy as np

In [1]:
N = ord("Y") % 15 + 1
print(N)

15


# Task 1

    Виконати набір вправ. Всі завдання виконати 2 способами: 
    а) з використанням універсальних функцій бібліотеки NumPy. 
    b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо). 

## **Вправа 1**
Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0. 

In [5]:
import time

In [6]:
def task_1():
    n = int(input("n: "))
    a = time.time()
    
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        matrix[i][i] = i + 1
    
    b = time.time()
    
    print("Час виконання (numpy): "+str(b-a)+"sec")
    print(matrix)

In [7]:
task_1()

n:  5


Час виконання (numpy): 0.0sec
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
def task_1_2():
    n = int(input("n: "))
    a = time.time()
    
    matrix = []                              
    for i in range(n):
        row = [0] * n          
        row[i] = i + 1         
        matrix = matrix + [row] 

    for row in matrix:
        print(row)
    
    b = time.time()
    
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [9]:
task_1_2()

n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
Час виконання (ітеративні конструкції): 0.0sec


## **Вправа 3** 
Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1. 

In [10]:
def task_3():
    n = int(input("n: "))
    m = int(input("m: "))
    r = int(input("r: "))
    c = int(input("c: "))

    a = time.time()
    
    matrix = np.ones((n, m), dtype=int)

    for i in range(n):
        for j in range(m):
            if (i % r == 0) or (j % c == 0):
                matrix[i, j] = 0
        
    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")
    print(matrix)

In [11]:
task_3()

n:  6
m:  7
r:  2
c:  3


Час виконання (numpy): 0.0sec
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [12]:
def task_3_2():
    n = int(input("n: "))
    m = int(input("m: "))
    r = int(input("r: "))
    c = int(input("c: "))
    a = time.time()

    matrix = []
    for i in range(n):
        row = []
        for j in range(m):
            if i % r == 0 or j % c == 0:
                row += [0]  
            else:
                row += [1]  
        matrix += [row]      

    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

    for row in matrix:
        print(row)

In [13]:
task_3_2()

n:  6
m:  7
r:  2
c:  3


Час виконання (ітеративні конструкції): 0.0sec
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]


## **Вправа 6**
З клавіатури вводиться масив. Замінити всі ненульові елементи на –1. 

In [20]:
def task_6():
    n = input("Введіть елементи масиву: ")
    a = time.time()
    array = []

    for i in n.split():
        array.append(int(i)) 

    arr = np.array(array)
    arr = np.where(arr != 0, -1, arr)

    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")
    print("Масив після заміни:", arr)

In [21]:
task_6()

Введіть елементи масиву:  3 4 0 6 5 0 3 0 4


Час виконання (numpy): 0.0sec
Масив після заміни: [-1 -1  0 -1 -1  0 -1  0 -1]


In [22]:
def task_6_2():
    n = input("Введіть елементи масиву: ")
    a = time.time()
    
    array = []
    for i in n.split():
        array.append(int(i))

    for i in range(len(array)):
        if array[i] != 0:
            array[i] = -1    
            
    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")
    print(array)

In [23]:
task_6_2()

Введіть елементи масиву:  3 4 0 6 5 0 3 0 4


Час виконання (ітеративні конструкції): 0.0sec
[-1, -1, 0, -1, -1, 0, -1, 0, -1]


## **Вправа 8**
З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів. 

In [24]:
def task_8_2():
    n = input("Введіть значення: ")
    a = time.time()

    count_zeros = 0
    count_numbers = 0
    
    for i in n:
        if i != ' ':
            if i == '0':
                count_zeros += 1
            else:
                count_numbers += 1
                
    b = time.time()
    print("Нулів: ", count_zeros)
    print("Не нулів: ", count_numbers)
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [25]:
task_8_2()

Введіть значення:  3 4 0 9 8 2 4 0 8 4 0


Нулів:  3
Не нулів:  8
Час виконання (ітеративні конструкції): 0.0sec


In [32]:
def task_8():
    n = input("Введіть числа через пробіл: ")
    a = time.time()
    array = n.split()
    
    arr = []
    for num in array:
        arr.append(int(num))
    
    k = np.array(arr)
    zero_count = np.count_nonzero(k == 0)
    nonzero_count = np.count_nonzero(k)

    b = time.time()
    print("Нулів: ", zero_count)
    print("Не нулів: ", nonzero_count)
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [33]:
task_8()

Введіть числа через пробіл:  3 4 0 9 8 2 4 0 8 4 0


Нулів:  3
Не нулів:  8
Час виконання (numpy): 0.0sec


## **Вправа 13**
Розмістити на полі 8×8 нулі та одиниці в шахматному порядку, використовуючи функцію повторення (*). 

In [34]:
def task_13():
    a = time.time()
    row1 = np.array([0, 1] * 4)  
    row2 = np.array([1, 0] * 4)  

    k = np.array([row1, row2] * 4)  
    b = time.time()
    print(k)
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [35]:
task_13()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Час виконання (numpy): 0.0sec


In [36]:
def task_13_2():
    a = time.time()
    for i in range(8): 
        if i % 2 == 0:
            print([0, 1] * 4)  
        else:
            print([1, 0] * 4)  
            
    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [37]:
task_13_2()

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
Час виконання (ітеративні конструкції): 0.0sec


## **Вправа 15**
Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [38]:
def task_15():
    n = int(input("Введіть n: "))
    a = time.time()
    
    m = np.zeros((n, n), dtype=int)
    
    m[:, 1::2] = 1
    
    print(m)
    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [39]:
task_15()

Введіть n:  5


[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Час виконання (numpy): 0.0sec


In [40]:
def task_15_2():
    n = int(input("Введіть n: "))
    a = time.time()
    matrix = []

    for i in range(n):
        row = []
        for j in range(n):
            if j % 2 == 1:  
                row.append(1)
            else:          
                row.append(0)
        matrix.append(row)

    for row in matrix:
        print(row)

    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [41]:
task_15_2()

Введіть n:  5


[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
Час виконання (ітеративні конструкції): 0.0sec


## **Вправа 16**
Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями. 

In [42]:
def task_16():
    n = int(input("Введіть n:"))
    a = time.time()
    vector = np.arange(n + 1)

    vector = np.where((vector > n/4) & (vector < 3*n/4), 0, vector)
    print(vector)
    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [43]:
task_16()

Введіть n: 10


[ 0  1  2  0  0  0  0  0  8  9 10]
Час виконання (numpy): 0.0003733634948730469sec


In [44]:
def task_16_2():
    n = int(input("Введіть значення: "))
    a = time.time()
    vector = []

    for i in range(n + 1):
        vector.append(i)

    for i in range(n):
        if n/4 < vector[i] < 3*n/4:
            vector[i] = 0

    print(vector)
    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [45]:
task_16_2()

Введіть значення:  10


[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
Час виконання (ітеративні конструкції): 0.0sec


## **Вправа 18**
Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності. 

In [46]:
import random

def task_18():
    n = int(input("Введіть значення: "))
    a = time.time()
    vector = np.random.randint(0, 99, n)

    unique = []  

    for i in vector:
        if np.count_nonzero(vector == i) == 1:
            unique.append(i)

    print("В послідовності", vector,f"- {len(unique)} унікальних чисел")
    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [46]:
task_18()

Введіть значення:  30


В послідовності [30 81 27 14 11 51 87 56 19  8 97 86 90 83 75 48 21 78 91 51 31 37 14 48
  6 80 69 37 82 17] - 22 унікальних чисел
Час виконання (numpy): 0.0018434524536132812sec


In [51]:
def task_18_2():
    n = int(input("Введіть значення: "))
    a = time.time()
    
    arr = []
    for i in range(n):
        arr.append(random.randint(0, 99))

    vector = []
    for i in range(len(arr)):
        if arr.count(arr[i]) == 1:
            vector.append(arr[i])

    print("В послідовності", vector,f"- {len(vector)} унікальних чисел")
    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [52]:
task_18_2()

Введіть значення:  30


В послідовності [13, 45, 72, 73, 97, 42, 19, 93, 68, 41, 76, 0, 64, 48, 46, 67, 78, 44, 62, 55, 27, 30, 80, 12, 5] - 25 унікальних чисел
Час виконання (ітеративні конструкції): 0.0012645721435546875sec


## **Вправа 20**
Згенерувати вектор із n  випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [53]:
def task_20():
    n = int(input("Введіть значення: "))
    a = time.time()
    
    vector = np.random.random(n)
    print("Початковий вектор:", vector)

    max_index = np.argmax(vector)  
    vector[max_index] = 0        

    print("Змінений вектор:", vector)
    b = time.time()
    print("Час виконання (numpy): "+str(b-a)+"sec")

In [54]:
task_20()

Введіть значення:  5


Початковий вектор: [0.64127836 0.80351521 0.52653556 0.00347658 0.98337379]
Змінений вектор: [0.64127836 0.80351521 0.52653556 0.00347658 0.        ]
Час виконання (numpy): 0.012825489044189453sec


In [47]:
def task_20_2():
    n = int(input("Введіть значення: "))
    a = time.time()

    vector = []  
    for i in range(n):   
        vector.append(random.random())
        
    max_el = max(vector) 
    print("Початковий вектор:", vector)
        
    for i in range(len(vector)):   
        if vector[i] == max_el:  
            vector[i] = 0         

    print("Змінений вектор:", vector)
    b = time.time()
    print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

In [48]:
task_20_2()

Введіть значення:  5


Початковий вектор: [0.6064909172659353, 0.4072028851233509, 0.3006721614762252, 0.4363132760050078, 0.01064423364927336]
Змінений вектор: [0, 0.4072028851233509, 0.3006721614762252, 0.4363132760050078, 0.01064423364927336]
Час виконання (ітеративні конструкції): 0.001026153564453125sec


# Task 2
    Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою: 
    a) матричного множення; 
    b) оберненої матриці; 
    c) функції numpy.linalg.solve(). 
    Порівняти всі рішення за допомогою функції numpy.allclose(). 

$$
\begin{cases} 
2x_1 - 6x_2 + 2x_3 + 2x_4 = 12 \\ 
x_1 + 3x_2 + 5x_3 + 7x_4 = 12 \\ 
3x_1 + 5x_2 + 7x_3 + x_4 = 0 \\ 
5x_1 + 7x_2 + x_3 + 3x_4 = 4 
\end{cases}
$$


$$
\Delta = \begin{vmatrix}
2 & -6 & 2 & 2 \\
1 & 3 & 5 & 7 \\
3 & 5 & 7 & 1 \\
5 & 7 & 1 & 3
\end{vmatrix}
$$                                     

$$
x_1 = \frac{\Delta_1}{\Delta}, \quad
x_2 = \frac{\Delta_2}{\Delta}, \quad
x_3 = \frac{\Delta_3}{\Delta}, \quad
x_4 = \frac{\Delta_4}{\Delta}
$$

$$
x_i = \frac{\Delta_i}{\Delta}, \quad i = 1,2,3,4
$$

де $\Delta_i$ - визначник матриці, отриманої заміною $i$-го стовпця на стовпець вільних членів.

In [23]:
import random
A = np.array([[2, -6, 2, 2],
              [1, 3, 5, 7],
              [3, 5, 7, 1],
              [5, 7, 1, 3]])

B = np.array([12, 12, 0, 4])

print("Matrix A:\n", A)
print("Column of free members:\n", B)
print("\nSolution by Cramer's method:")

det_A = np.linalg.det(A)
print(f"det(A) = {det_A:.2f}")

A_1 = A.copy()
A_1[:, 0] = B
det_A_1 = np.linalg.det(A_1)
print(f"det(A1) = {det_A_1:.2f}")
A_2 = A.copy()
A_2[:, 1] = B
det_A_2 = np.linalg.det(A_2)
print(f"det(A2) = {det_A_2:.2f}")
A_3 = A.copy()
A_3[:, 2] = B
det_A_3 = np.linalg.det(A_3)
print(f"det(A3) = {det_A_3:.2f}")
A_4 = A.copy()
A_4[:, 3] = B
det_A_4 = np.linalg.det(A_4)
print(f"det(A4) = {det_A_4:.2f}")

x_1 = det_A_1 / det_A
x_2 = det_A_2 / det_A
x_3 = det_A_3 / det_A
x_4 = det_A_4 / det_A

x_Cramer = np.array([x_1, x_2, x_3, x_4])
x_Cramer_f = np.round(x_Cramer, 2)
print(f"\nAnswers:")
print(f"x₁ = {det_A_1:.2f}/{det_A:.2f} = {x_1:.2f}")
print(f"x₂ = {det_A_2:.2f}/{det_A:.2f} = {x_2:.2f}")
print(f"x₃ = {det_A_3:.2f}/{det_A:.2f} = {x_3:.2f}")
print(f"x₄ = {det_A_4:.2f}/{det_A:.2f} = {x_4:.2f}")
print(f"x = {x_Cramer_f}")

Matrix A:
 [[ 2 -6  2  2]
 [ 1  3  5  7]
 [ 3  5  7  1]
 [ 5  7  1  3]]
Column of free members:
 [12 12  0  4]

Solution by Cramer's method:
det(A) = -2048.00
det(A1) = -2048.00
det(A2) = 2048.00
det(A3) = 0.00
det(A4) = -4096.00

Answers:
x₁ = -2048.00/-2048.00 = 1.00
x₂ = 2048.00/-2048.00 = -1.00
x₃ = 0.00/-2048.00 = -0.00
x₄ = -4096.00/-2048.00 = 2.00
x = [ 1. -1. -0.  2.]


In [25]:
print("Matrix multiplication")

verification = A @ x_Cramer_f
print(f"Initial B:\n", B)
print(f"Check:\n {verification}")

Matrix multiplication
Initial B:
 [12 12  0  4]
Check:
 [12. 12.  0.  4.]


In [29]:
print("Inverse matrix")

A_inv = np.linalg.inv(A)
x_inv = A_inv @ B
print(f"Inverse matrix A^-1\n")
print(np.round(A_inv, 4))
print(f"\nCheck - A^-1 * B: ")
print(np.round(x_inv, 4))

Inverse matrix
Inverse matrix A^-1

[[ 0.1406 -0.1094  0.0156  0.1562]
 [-0.1094  0.0156  0.0156  0.0312]
 [ 0.0156  0.0156  0.1406 -0.0938]
 [ 0.0156  0.1406 -0.1094  0.0313]]

Check - A^-1 * B: 
[ 1. -1. -0.  2.]


In [31]:
print("Function numpy.linalg.solve")

x = np.linalg.solve(A, B)
print(np.round(x, 4))

Function numpy.linalg.solve
[ 1. -1. -0.  2.]


In [32]:
print("Comparasion of solutions with numpy.allclose(): ")
print(f"Cramer's method and Inverse matrix: {np.allclose(x_Cramer_f, x_inv)}")
print(f"Cramer's method and function linalg.solve: {np.allclose(x_Cramer_f, x)}")
print(f"Inverse matrix and function linalg.solve: {np.allclose(x_inv, x)}")

Comparasion of solutions with numpy.allclose(): 
Cramer's method and Inverse matrix: True
Cramer's method and function linalg.solve: True
Inverse matrix and function linalg.solve: True


# Task 3
    Обчислити значення матричного виразу  
    а) з використанням універсальних функцій бібліотеки NumPy. 
    b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо). 
    с) для обох випадків підрахувати час виконання скрипту та зробити висновок. 
    Порівняти всі рішення за допомогою функції numpy.allclose().
 $ 3(A+B)(AB-2A) $, 
$ A = \begin{pmatrix}
2 & 1 & 3 \\
1 & -2 & 0 \\
4 & -3 & 0
\end{pmatrix} $, 
$ B = \begin{pmatrix}
22 & -14 & 3 \\
6 & -7 & 0 \\
11 & 3 & 15
\end{pmatrix} $

In [38]:
a = time.time()
A = np.array([[2, 1, 3],
              [1, -2, 0],
              [4, -3, 0]])

B = np.array([[22, 14, 3],
              [6, -7, 0],
              [11, 3, 15]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

calculation = 3 * (A + B) @ (A @ B - 2 * A)
print("Result:\n", calculation)
b = time.time()
print("Час виконання (numpy): "+str(b-a)+"sec")



Matrix A:
 [[ 2  1  3]
 [ 1 -2  0]
 [ 4 -3  0]]
Matrix B:
 [[22 14  3]
 [ 6 -7  0]
 [11  3 15]]
Result:
 [[7164 4950 3591]
 [1443 -276  864]
 [6345 4995 2565]]
Час виконання (numpy): 0.0sec


In [40]:
A = [[2, 1, 3],
     [1, -2, 0],
     [4, -3, 0]]

B = [[22, 14, 3],
     [6, -7, 0],
     [11, 3, 15]]

a = time.time()
n = 3
res = [[0] * 3 for _ in range(3)]

for i in range(3):
    for j in range(3):
        total = 0
        for k in range(3):
            a_plus_b = A[i][k] + B[i][k]
            ab = sum(A[k][m] * B[m][j] for m in range(3))
            ab_minus_2a = ab - 2 * A[k][j]
            total += a_plus_b * ab_minus_2a
        res[i][j] = 3 * total

print("Result:\n")
for row in res:
    print(row)
    
b = time.time()
print("Час виконання (ітеративні конструкції): "+str(b-a)+"sec")

Result:

[7164, 4950, 3591]
[1443, -276, 864]
[6345, 4995, 2565]
Час виконання (ітеративні конструкції): 0.0010004043579101562sec


In [41]:
print("Comparasion of solutions with numpy.allclose(): ")
print(f"Using Numpy and loops: {np.allclose(calculation, res)}")

Comparasion of solutions with numpy.allclose(): 
Using Numpy and loops: True
